# - 作成日: 2026-09-27
# - 目的: 既存VS Codeから起動するNotebook専用Pythonへ保存先と並列数を渡す。
# - 役割: env.cmdの設定値から.venv内の起動フックを生成・確認・解除する。
# - 使用: call env.cmd configure / check / unconfigure。直接起動は-I -B -Sが必要。
# - 制約: 固定配置、GIL付きCPython 3.14.7、Windows AMD64。標準ライブラリのみ。
# - 非対応: VS Code起動、依存導入、他の環境、-SでのNotebook実行、認証情報の移行。
import hashlib
import json
import os
import platform
import subprocess
import sys
from pathlib import Path

# - 値はenv.cmdを原本とし、この一覧は出力を許可する非秘密のキーだけを定める。
RUNTIME_KEYS = (
    "UV_CACHE_DIR", "UV_PYTHON_INSTALL_DIR", "UV_PYTHON_BIN_DIR",
    "UV_PYTHON_INSTALL_BIN", "UV_PYTHON_INSTALL_REGISTRY", "UV_PROJECT_ENVIRONMENT",
    "UV_PYTHON", "UV_PYTHON_DOWNLOADS", "PYTHONUTF8", "PYTHONNOUSERSITE",
    "PYTHONDONTWRITEBYTECODE", "PYTHONUSERBASE", "TEMP", "TMP", "MPLCONFIGDIR",
    "NUMBA_CACHE_DIR", "PYTENSOR_FLAGS", "TORCH_HOME", "TORCH_EXTENSIONS_DIR",
    "SEABORN_DATA", "XDG_CONFIG_HOME", "XDG_CACHE_HOME", "XDG_DATA_HOME",
    "MARIMO_SKIP_UPDATE_CHECK", "UV_CONCURRENT_DOWNLOADS", "UV_CONCURRENT_INSTALLS",
    "UV_CONCURRENT_BUILDS", "OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS",
    "MKL_NUM_THREADS", "NUMBA_NUM_THREADS", "POLARS_MAX_THREADS",
)
# - uvのWindowsランチャーが設定する正当なPYTHONHOMEは検証後に子へ残さない。
CLEAR_KEYS = ("PYTHONHOME", "VIRTUAL_ENV", "UV_CONFIG_FILE", "UV_INDEX", "UV_INDEX_URL",
              "UV_EXTRA_INDEX_URL", "UV_DEFAULT_INDEX")
# - log配下へ移動しても、環境と生成物の基準はプロジェクト直下に保つ。
ROOT = Path(__file__).resolve().parents[1]
VENV = ROOT / ".venv"
SITE = VENV / "Lib" / "site-packages"
STATE = ROOT / ".cache" / "runtime-registration.json"
FILES = (SITE / "_bayes_runtime.py", SITE / "000_bayes_runtime.pth")
MARKER = "# Generated by configure_runtime.py; bayes-runtime-v1\n"


def validate_runtime() -> None:
    """実行系を確認する。引数・戻り値・副作用なし。前提はenv.cmd経由。
    不一致時はRuntimeError。例: 登録前にvalidate_runtime()を呼ぶ。
    """
    # - コピー先・別Python・起動済みフックからの実行を拒否し、所有範囲を限定する。
    if (ROOT != Path("C:/dev/python_bayes_intro/marimo/2026")
            or Path(sys.prefix).resolve() != VENV
            or Path(sys.executable).resolve() != VENV / "Scripts" / "python.exe"
            or sys.version_info[:3] != (3, 14, 7)
            or platform.python_implementation() != "CPython"
            or platform.machine() != "AMD64" or sys.platform != "win32"
            or not sys._is_gil_enabled() or not sys.flags.no_site):
        raise RuntimeError("Use call env.cmd with the project's GIL-enabled CPython 3.14.7.")


def read_values() -> dict[str, str]:
    """許可した設定値を取得する。引数なし。戻り値は環境変数の辞書。
    前提はenv.cmd適用済み。副作用なし。不足・範囲外はRuntimeError。
    例: values = read_values()。全環境変数や認証情報は収集しない。
    """
    values = {}
    # - 明示したキーだけを取得し、任意の親環境を保存しない。
    for key in RUNTIME_KEYS:
        value = os.environ.get(key, "")
        # - 空値・改行は壊れた設定として登録前に止める。
        if not value or "\n" in value or "\r" in value:
            raise RuntimeError(f"Missing or invalid {key}; run call env.cmd configure.")
        values[key] = value
    profile = Path(os.environ.get("BAYES_RUNTIME_PROFILE", ""))
    # - Notebook側の個人領域だけを固定し、VS Codeやターミナルの認証状態を保つ。
    if profile != ROOT / ".cache" / "profile":
        raise RuntimeError("Invalid Notebook profile location.")
    values.update(USERPROFILE=str(profile), APPDATA=str(profile / "AppData/Roaming"),
                  LOCALAPPDATA=str(profile / "AppData/Local"))
    # - 保存先はROOT以下だけを認め、数値などの設定と区別する。
    for key, value in values.items():
        candidate = value.removeprefix("base_compiledir=")
        # - Windowsの絶対パスを使う項目を検査し、範囲外への誘導を防ぐ。
        if ":" in candidate:
            path = Path(candidate).resolve()
            # - Python実行系も含め、このプロジェクト外は使用しない。
            if not path.is_relative_to(ROOT):
                raise RuntimeError(f"Path outside the project: {key}")
    return values


def render(values: dict[str, str]) -> dict[Path, bytes]:
    """起動コードを生成する。引数は許可済み設定、戻り値は保存先とUTF-8内容。
    前提は値の検証済み。副作用なし。例: render(read_values())。変換エラーは伝搬。
    """
    source = MARKER + f'''import os
import sys
if os.path.normcase(os.path.abspath(sys.prefix)) != {os.path.normcase(str(VENV))!r}:
    raise SystemExit("ERROR: This runtime hook belongs to another environment.")
home = os.environ.get("PYTHONHOME")
if (home and os.path.normcase(os.path.abspath(home)) != os.path.normcase(sys.base_prefix)) or os.environ.get("PYTHONPATH"):
    raise SystemExit("ERROR: Clear inherited PYTHONHOME/PYTHONPATH before using this kernel.")
os.environ.update({values!r})
for key in {CLEAR_KEYS!r}:
    os.environ.pop(key, None)
sys.dont_write_bytecode = True
'''
    # - フック欠落時の黙った継続を防ぎ、-Sの登録器から修復できる状態で停止する。
    loader = ('try:\n import _bayes_runtime\nexcept Exception:\n'
              ' raise SystemExit("ERROR: Invalid runtime registration. Run call env.cmd configure.") from None\n')
    pth = MARKER + f"import sys; sys.dont_write_bytecode = True; exec({loader!r})\n"
    return {FILES[0]: source.encode("utf-8"), FILES[1]: pth.encode("utf-8")}


def owned_files() -> dict[str, str]:
    """既存生成物の所有を検査する。引数なし。戻り値は保存済みハッシュ。
    前提は操作ロック取得済み。読取のみ。競合はRuntimeError。例: owned_files()。
    """
    # - 初回は他者の同名ファイルを採用せず、専用名の衝突として扱う。
    if not STATE.exists():
        # - 登録記録がない生成物は所有を証明できない。
        if any(path.exists() for path in FILES):
            raise RuntimeError("Unowned runtime files exist; preserve them and inspect manually.")
        return {}
    hashes = json.loads(STATE.read_text(encoding="utf-8"))
    # - 記録から任意の削除先を受け取らず、固定した2ファイルだけを検査する。
    if (not isinstance(hashes, dict) or set(hashes) != {path.name for path in FILES}
            or any(not isinstance(value, str) or len(value) != 64 for value in hashes.values())):
        raise RuntimeError("Invalid registration record; inspect the backup before recovery.")
    # - .venv再作成で2本とも消えた場合は、残った記録から安全に再登録できる。
    if not any(path.exists() for path in FILES):
        return hashes
    # - 不在・利用者による変更は上書きも削除もしない。
    for path in FILES:
        # - 手編集や片方だけの削除は、自動修復で隠さず停止する。
        if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != hashes[path.name]:
            raise RuntimeError("Runtime files changed; preserve them and inspect the backup.")
    return hashes


def verify(values: dict[str, str], expected: dict[Path, bytes]) -> None:
    """登録と新規Pythonを確認する。引数は設定と期待する生成物。戻り値なし。
    前提は所有検査済み。子プロセス1つを最大30秒実行。不一致はRuntimeError。
    例: verify(values, render(values))。画面操作やログイン状態は検査しない。
    """
    # - env.cmd変更後に登録を更新し忘れた場合を検出する。
    for path, data in expected.items():
        # - 欠落・古い内容ではカーネル再起動を促す前に再登録を要求する。
        if not path.is_file() or path.read_bytes() != data:
            raise RuntimeError("Runtime configuration is missing or stale; run call env.cmd configure.")
    probe = ("import os,sys,tempfile,site; expected=" + repr(values)
             + "; assert all(os.environ.get(k)==v for k,v in expected.items());"
             + " assert tempfile.gettempdir()==expected['TEMP'];"
             + " assert sys.dont_write_bytecode and not site.ENABLE_USER_SITE;"
             + " print('Passed: runtime values, local temp, bytecode and user-site isolation')")
    clean = dict(os.environ)
    # - ターミナルからの継承に依存せず、フックが値を設定できることを確認する。
    for key in RUNTIME_KEYS:
        clean.pop(key, None)
    probe_temp = ROOT / ".cache" / "wrong-temp-probe"
    probe_temp.mkdir(exist_ok=True)
    clean["TEMP"] = clean["TMP"] = str(probe_temp)
    result = subprocess.run([sys.executable, "-I", "-B", "-c", probe], env=clean,
                            cwd=ROOT, capture_output=True, text=True, encoding="utf-8", timeout=30)
    # - 子の環境全体や個人情報を出力せず、終了コードで異常を伝える。
    if result.returncode or result.stderr:
        raise RuntimeError("Fresh-process runtime verification failed; inspect project configuration.")
    print(result.stdout.strip())


def main() -> None:
    """指定操作を実行する。引数はsys.argvの操作名、戻り値なし。
    前提はenv.cmd経由。生成物2本・記録・退避を更新する。競合・I/O失敗は例外。
    例: call env.cmd configure。ロックは自分で取得した場合だけ解除する。
    """
    validate_runtime()
    action = sys.argv[1].lower() if len(sys.argv) == 2 else ""
    # - 不正な操作ではファイルを変更しない。
    if action not in {"configure", "check", "unconfigure"}:
        raise RuntimeError("Expected configure, check, or unconfigure.")
    STATE.parent.mkdir(parents=True, exist_ok=True)
    lock = STATE.with_suffix(".lock")
    # - 同時設定を拒否する。既存ロックは別所有者の可能性があるため削除しない。
    with lock.open("x", encoding="utf-8") as handle:
        handle.write("Runtime configuration in progress\n")
    # - 所有するロックを成功・失敗にかかわらず最後に解除する。
    try:
        hashes = owned_files()
        # - 解除は所有が確認できたファイルだけを退避して行う。
        if action == "unconfigure":
            # - 未登録なら何も削除せず正常終了する。
            if hashes:
                backup = STATE.parent / "runtime-before-unconfigure"
                backup.mkdir(exist_ok=True)
                # - 既存の退避と異なる場合は保全して停止する。
                for path in (*FILES, STATE):
                    # - .venv再作成直後に既に消えた生成物は、退避・削除の対象にしない。
                    if not path.exists():
                        continue
                    target = backup / path.name
                    # - 手元の退避を無断で置き換えない。
                    if target.exists() and target.read_bytes() != path.read_bytes():
                        raise RuntimeError("Previous removal backup differs; preserve it before proceeding.")
                    target.write_bytes(path.read_bytes())
                # - 全退避成功後に、固定された所有ファイルだけを解除する。
                for path in (*FILES, STATE):
                    # - 不在の生成物を新たに作成してから消すことはしない。
                    if path.exists():
                        path.unlink()
            print("Passed: runtime registration removed; stop using kernels until configured again")
            return
        values = read_values()
        expected = render(values)
        # - configureだけが生成物を更新する。checkは内容を変更しない。
        if action == "configure":
            # - 更新前の生成物を保存し、別ファイルとして追跡できるようにする。
            for path, data in expected.items():
                # - 内容が同じなら再生成せず、カーネルの読取と衝突させない。
                if path.exists() and path.read_bytes() == data:
                    continue
                # - 既存版は内容ハッシュ名で保存して上書きしない。
                if path.exists():
                    saved = STATE.parent / (path.name + "." + hashes[path.name] + ".bak")
                    saved.write_bytes(path.read_bytes())
                temporary = path.with_suffix(path.suffix + ".tmp")
                temporary.write_bytes(data)
                temporary.replace(path)
            record = {path.name: hashlib.sha256(data).hexdigest() for path, data in expected.items()}
            record_temp = STATE.with_suffix(".json.tmp")
            record_temp.write_text(json.dumps(record, indent=2), encoding="utf-8")
            record_temp.replace(STATE)
        verify(values, expected)
        print("Passed: restart the Notebook kernel to apply registered settings")
    # - 処理全体の原子性は主張せず、自分の操作ロックだけ確実に解除する。
    finally:
        lock.unlink()


# - 登録器は-Sで実行し、起動フックから自分自身を呼び出さない。
if __name__ == "__main__":
    # - 個人パスや環境変数一覧を含むトレースを表示せず、操作失敗を返す。
    try:
        main()
    # - 通常の失敗は英語の案内と終了コード1で返す。
    except (OSError, RuntimeError, ValueError, subprocess.SubprocessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)
